/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface2.h"

bool_t
xdr_estado_subasta (XDR *xdrs, estado_subasta *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_estado_producto_subasta (XDR *xdrs, estado_producto_subasta *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_producto (XDR *xdrs, nodo_producto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->codigoProducto))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAX_NOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valor))
		 return FALSE;
	 if (!xdr_estado_producto_subasta (xdrs, &objp->estadoProd))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tipo_usuario_comprador (XDR *xdrs, tipo_usuario_comprador *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_completos_comprador (XDR *xdrs, datos_completos_comprador *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombres, MAX_NOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->apellidos, MAX_NOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->correo, MAXCORREO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->telefono, MAXTEL,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->login, MAX_NOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->contrasenia, MAX_NOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_tipo_usuario_comprador (xdrs, &objp->tipo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_oferta (XDR *xdrs, oferta *objp)
{
	register int32_t *buf;

	 if (!xdr_datos_completos_comprador (xdrs, &objp->objUsuario_comprador_actual))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valor))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_subasta (XDR *xdrs, nodo_subasta *objp)
{
	register int32_t *buf;

	 if (!xdr_nodo_producto (xdrs, &objp->prod))
		 return FALSE;
	 if (!xdr_oferta (xdrs, &objp->oferta_actual))
		 return FALSE;
	 if (!xdr_estado_subasta (xdrs, &objp->estado))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vector_productos (XDR *xdrs, vector_productos *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->vector_productos, MAX_CAN_PROD,
		sizeof (nodo_producto), (xdrproc_t) xdr_nodo_producto))
		 return FALSE;
	return TRUE;
}
