/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "interface2.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

bool_t *
registrar_producto_2(nodo_producto *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, registrar_producto,
		(xdrproc_t) xdr_nodo_producto, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vector_productos *
listarproductosdisponiblessubastar_2(void *argp, CLIENT *clnt)
{
	static vector_productos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, listarProductosDisponiblesSubastar,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_vector_productos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
abrircerrarsubasta_2(int *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, abrirCerrarSubasta,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vector_productos *
listarproductostodos_2(void *argp, CLIENT *clnt)
{
	static vector_productos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, listarProductosTodos,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_vector_productos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nodo_producto *
consultarproducto_2(int *argp, CLIENT *clnt)
{
	static nodo_producto clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarProducto,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_nodo_producto, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nodo_subasta *
consultarproductoandvaloractualsubasta_2(void *argp, CLIENT *clnt)
{
	static nodo_subasta clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarProductoAndValorActualSubasta,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_nodo_subasta, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
ofertarproductosubasta_2(oferta *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ofertarProductoSubasta,
		(xdrproc_t) xdr_oferta, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
