/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface2.h"

bool_t *
registrar_producto_2_svc(nodo_producto *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

vector_productos *
listarproductosdisponiblessubastar_2_svc(void *argp, struct svc_req *rqstp)
{
	static vector_productos  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
abrircerrarsubasta_2_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

vector_productos *
listarproductostodos_2_svc(void *argp, struct svc_req *rqstp)
{
	static vector_productos  result;

	/*
	 * insert server code here
	 */

	return &result;
}

nodo_producto *
consultarproducto_2_svc(int *argp, struct svc_req *rqstp)
{
	static nodo_producto  result;

	/*
	 * insert server code here
	 */

	return &result;
}

nodo_subasta *
consultarproductoandvaloractualsubasta_2_svc(void *argp, struct svc_req *rqstp)
{
	static nodo_subasta  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
ofertarproductosubasta_2_svc(oferta *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}
