/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"

bool_t *
registrarusuario_1_svc(datos_completos *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

respuesta_login *
iniciarsesion_1_svc(datos_login *argp, struct svc_req *rqstp)
{
	static respuesta_login  result;

	/*
	 * insert server code here
	 */

	return &result;
}
