/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"
#include "interface2.h"
void menuGestionUsuarios()
{
	printf("\n====== menu ======");
	printf("\n 1. Registrar usuario.");
	printf("\n 2. Iniciar sesion.");
	printf("\n 3. Salir.");
}

void menuSubastaCliente()
{
	printf("\n====== menu cliente======");
	printf("\n 1. Listar todos los productos.");
	printf("\n 2. Consultar producto por codigo.");
	printf("\n 3. Consultar producto acual subastadose.");
	printf("\n 4. Ofertar al producto actual subastandose.");
	printf("\n 5. Salir.");
}
void
gestion_usuarios_1(char *host)
{
	CLIENT *clnt1;
	bool_t  *result_1;
	datos_completos  registrarusuario_1_arg;
	respuesta_login  *result_2;
	datos_login  iniciarsesion_1_arg;
	CLIENT *clnt2;
	bool_t  *result_3;
	nodo_producto  registrar_producto_2_arg;
	vector_productos  *result_4;
	char *listarproductosdisponiblessubastar_2_arg;
	bool_t  *result_5;
	int  abrircerrarsubasta_2_arg;
	vector_productos  *result_6;
	char *listarproductostodos_2_arg;
	nodo_producto  *result_7;
	int  consultarproducto_2_arg;
	nodo_subasta  *result_8;
	char *consultarproductoandvaloractualsubasta_2_arg;
	bool_t  *result_9;
	oferta  ofertarproductosubasta_2_arg;
	int opcion;


#ifndef	DEBUG
	clnt1 = clnt_create (host, gestion_usuarios, gestion_usuarios_version_1, "udp");
	if (clnt1 == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registrarusuario_1(&registrarusuario_1_arg, clnt1);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror(clnt1, "call failed");
	}
	result_2 = iniciarsesion_1(&iniciarsesion_1_arg, clnt1);
	if (result_2 == (respuesta_login *) NULL) {
		clnt_perror(clnt1, "call failed");
	}
	#ifndef	DEBUG
	clnt2 = clnt_create (host, gestion_subastas, gestion_subastas_version_1, "tcp");
	if (clnt2 == NULL) {
		clnt_pcreateerror(host);
		exit (1);
	}
#endif	/* DEBUG */
	//invocacion de los procedimientos remotos
	do
	{
		menuGestionUsuarios();
		printf("\n Digite una opcion: ");
		scanf("%d", &opcion);
		switch (opcion)
		{
		case 1:
			//TODO
			break;
		case 2:
			while (result_2->codigo != 1) {
				printf("\nIngrese el login: ");
				scanf("%s", iniciarsesion_1_arg.login);
				fflush(stdin);
				printf("Ingrese la constrasenia: ");
				scanf("%s", iniciarsesion_1_arg.contrasenia);
				fflush(stdin);
				result_2 = iniciarsesion_1(&iniciarsesion_1_arg, clnt1);
				fflush(stdin);
				if(result_2->codigo != 1){
					printf("\n%s",result_2->mensaje);
				}
				if (result_2 == (respuesta_login *) NULL) {
					clnt_perror(clnt1, "call failed");
				}
				if (result_2->codigo == 1)
				{
					do
					{
						menuSubastaCliente();
						printf("\n Digite una opcion: ");
						scanf("%d", &opcion);
						switch (opcion)
						{
						case 1:
							printf("Digite el codigo: "); 
							scanf("%d", &registrar_producto_2_arg.codigoProducto);

							printf("Digite el nombre: "); 
							scanf("%s", registrar_producto_2_arg.nombre);

							printf("Digite el valor: "); 
							scanf("%f",&registrar_producto_2_arg.valor); 
							result_3 = registrar_producto_2(&registrar_producto_2_arg, clnt2); 
							if (result_3 == (bool_t *) NULL) { 
								clnt_perror (clnt2, "call failed");
							} 
							else if(*result_3==TRUE)
							{
								printf("\n Producto registrado exitosamente");
							}	
							break;
						case 2:
							printf("Digite el id: ");
							scanf("%d", &consultarproducto_2_arg);

							result_7 = consultarproducto_2(&consultarproducto_2_arg, clnt2);
							if (result_7 == (nodo_producto *) NULL) {
								clnt_perror (clnt2, "call failed");
							}
							else
							{
								printf("\nCodigo: %d", result_7->codigoProducto);
								printf("\nNombre: %s", result_7->nombre);
								printf("\nValor: %f", result_7->valor);
							}
							break;
						case 3:
							printf("\nSaliendo del programa.");				
							break;
						default:
							break;
						}
					} while (opcion != 3);
					
				}
	
			}
			break;
		
		default:
			break;
		}
	} while (opcion!=3);
	 
	
	
	result_3 = registrar_producto_2(&registrar_producto_2_arg, clnt2);
	if (result_3 == (bool_t *) NULL) {
		clnt_perror(clnt2, "call failed");
	}
	result_4 = listarproductosdisponiblessubastar_2((void*)&listarproductosdisponiblessubastar_2_arg, clnt2);
	if (result_4 == (vector_productos *) NULL) {
		clnt_perror(clnt2, "call failed");
	}
	result_5 = abrircerrarsubasta_2(&abrircerrarsubasta_2_arg, clnt2);
	if (result_5 == (bool_t *) NULL) {
		clnt_perror(clnt2, "call failed");
	}
	result_6 = listarproductostodos_2((void*)&listarproductostodos_2_arg, clnt2);
	if (result_6 == (vector_productos *) NULL) {
		clnt_perror(clnt2, "call failed");
	}
	result_7 = consultarproducto_2(&consultarproducto_2_arg, clnt2);
	if (result_7 == (nodo_producto *) NULL) {
		clnt_perror(clnt2, "call failed");
	}
	result_8 = consultarproductoandvaloractualsubasta_2((void*)&consultarproductoandvaloractualsubasta_2_arg, clnt2);
	if (result_8 == (nodo_subasta *) NULL) {
		clnt_perror(clnt2, "call failed");
	}
	result_9 = ofertarproductosubasta_2(&ofertarproductosubasta_2_arg, clnt2);
	if (result_9 == (bool_t *) NULL) {
		clnt_perror(clnt2, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt1);
	clnt_destroy (clnt2);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_usuarios_1 (host);
exit (0);
}
