/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE1_H_RPCGEN
#define _INTERFACE1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 20
#define MAXCORREO 50
#define MAXTEL 10

enum tipo_usuario {
	ADMIN = 0,
	CLIENTE = 1,
};
typedef enum tipo_usuario tipo_usuario;

struct datos_completos {
	char nombres[MAXNOM];
	char apellidos[MAXNOM];
	char correo[MAXCORREO];
	char telefono[MAXTEL];
	char login[MAXNOM];
	char contrasenia[MAXNOM];
	tipo_usuario tipo;
};
typedef struct datos_completos datos_completos;

struct datos_login {
	char login[MAXNOM];
	char contrasenia[MAXNOM];
};
typedef struct datos_login datos_login;

struct respuesta_login {
	char mensaje[MAXNOM];
	int codigo;
	datos_completos objUsuario;
};
typedef struct respuesta_login respuesta_login;

#define gestion_usuarios 0x20000001
#define gestion_usuarios_version_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrarUsuario 1
extern  bool_t * registrarusuario_1(datos_completos *, CLIENT *);
extern  bool_t * registrarusuario_1_svc(datos_completos *, struct svc_req *);
#define iniciarSesion 2
extern  respuesta_login * iniciarsesion_1(datos_login *, CLIENT *);
extern  respuesta_login * iniciarsesion_1_svc(datos_login *, struct svc_req *);
extern int gestion_usuarios_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrarUsuario 1
extern  bool_t * registrarusuario_1();
extern  bool_t * registrarusuario_1_svc();
#define iniciarSesion 2
extern  respuesta_login * iniciarsesion_1();
extern  respuesta_login * iniciarsesion_1_svc();
extern int gestion_usuarios_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_tipo_usuario (XDR *, tipo_usuario*);
extern  bool_t xdr_datos_completos (XDR *, datos_completos*);
extern  bool_t xdr_datos_login (XDR *, datos_login*);
extern  bool_t xdr_respuesta_login (XDR *, respuesta_login*);

#else /* K&R C */
extern bool_t xdr_tipo_usuario ();
extern bool_t xdr_datos_completos ();
extern bool_t xdr_datos_login ();
extern bool_t xdr_respuesta_login ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE1_H_RPCGEN */
