/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"
#include "interface2.h"
void menuGestionUsuarios()
{
	printf("\n====== menu ======");
	printf("\n 1. Registrar usuario.");
	printf("\n 2. Iniciar sesion.");
	printf("\n 3. Salir.");
}
void menuSubastaAdmin()
{
	printf("\n====== menu admin======");
	printf("\n 1. Registrar producto");
	printf("\n 2. Listar productos a ofertar.");
	printf("\n 3. Abrir o Cerrar subasta.");
	printf("\n 4. Consultar producto por codigo.");
	printf("\n 5. Consultar producto actual subastadose.");
	printf("\n 6. Salir.");
}

void menuSubastaCliente()
{
	printf("\n====== menu cliente======");
	printf("\n 1. Listar todos los productos.");
	printf("\n 2. Consultar producto por codigo.");
	printf("\n 3. Consultar producto actual subastadose.");
	printf("\n 4. Ofertar al producto actual subastandose.");
	printf("\n 5. Salir.");
}

datos_completos registrarAdmin(){
	datos_completos  objUsuario;
	// Limpiar búfer de entrada
	fgets(objUsuario.nombres, MAXNOM, stdin);
	// Ingresar datos del administrador
	printf("\nIngrese nombres: ");
	fgets(objUsuario.nombres, MAXNOM, stdin);
	objUsuario.nombres[strcspn(objUsuario.nombres, "\n")] = '\0';
	fflush(stdin);

	printf("Ingrese apellidos: ");
	fgets(objUsuario.apellidos, MAXNOM, stdin);
	objUsuario.apellidos[strcspn(objUsuario.apellidos, "\n")] = '\0';
	fflush(stdin);
	
	printf("Ingrese correo electrónico: ");
	fgets(objUsuario.correo, MAXCORREO, stdin);
	objUsuario.correo[strcspn(objUsuario.correo, "\n")] = '\0';
	fflush(stdin);
	
	printf("Ingrese teléfono: ");
	fgets(objUsuario.telefono, MAXTEL, stdin);
	objUsuario.telefono[strcspn(objUsuario.telefono, "\n")] = '\0';
	fflush(stdin);
	
	printf("Ingrese nombre de usuario: ");
	fgets(objUsuario.login, MAXNOM, stdin);
	objUsuario.login[strcspn(objUsuario.login, "\n")] = '\0';
	fflush(stdin);
	
	printf("Ingrese contraseña: ");
	fgets(objUsuario.contrasenia, MAXNOM, stdin);
	objUsuario.contrasenia[strcspn(objUsuario.contrasenia, "\n")] = '\0';
	fflush(stdin);
	
	// Asignar tipo de usuario
	objUsuario.tipo = ADMIN;
	// Imprimir los datos del administrador ingresado
	printf("\nDatos del administrador ingresado:\n");
	printf("Nombres: %s\n", objUsuario.nombres);
	printf("Apellidos: %s\n", objUsuario.apellidos);
	printf("Correo electrónico: %s\n", objUsuario.correo);
	printf("Teléfono: %s\n", objUsuario.telefono);
	printf("Nombre de usuario: %s\n", objUsuario.login);
	printf("Contraseña: %s\n", objUsuario.contrasenia);									
	printf("Tipo de usuario: %s\n", objUsuario.tipo == ADMIN ? "ADMIN" : "CLIENTE");
	
	return objUsuario;
}

void registrarProducto(){

}
void listarProductosOfertar(){
    
}
void abrirOCerrarSubasta(nodo_subasta *result_8,char *consultarproductoandvaloractualsubasta_2_arg, bool_t *result_5,int abrircerrarsubasta_2_arg, CLIENT *clnt2){
	
	int opcionAbrirCerrar;
	result_8 = consultarproductoandvaloractualsubasta_2((void*)&consultarproductoandvaloractualsubasta_2_arg, clnt2);
	if (result_8 == (nodo_subasta *) NULL) {
		clnt_perror(clnt2, "call failed");
	}					
    
    if (result_8->estado == NUEVA || result_8->estado == CERRADA || result_8->prod.codigoProducto==-1) { // Si no hay una subasta actual
        printf("No hay una subasta abierta actualmente.\n");
        printf("Ingrese el codigo del producto a subastar: ");
        scanf("%d", &abrircerrarsubasta_2_arg);
        result_5 = abrircerrarsubasta_2(&abrircerrarsubasta_2_arg, clnt2);// Crear una nueva subasta con el producto especificado
		if (result_5 == (bool_t *) NULL) {
			clnt_perror(clnt2, "call failed");
		}
		if (*result_5==TRUE)
		{
        	printf("La subasta ha sido abierta exitosamente.\n");
		}else{
			printf("ERROR: La subasta no se pudo crear, el producto puede no estar disponible para subastar.\n");
		}
		 
    } else { // Si ya hay una subasta abierta
		abrircerrarsubasta_2_arg = result_8->prod.codigoProducto;	
        printf("La subasta actual es del producto con codigo %d.\n", abrircerrarsubasta_2_arg);
        printf("1. Cerrar subasta.\n");
        printf("2. Cancelar.\n");
        printf("Ingrese una opcion: ");
        scanf("%d", &opcionAbrirCerrar);
        switch (opcionAbrirCerrar) {
            case 1: // Cerrar subasta
                result_5 = abrircerrarsubasta_2(&abrircerrarsubasta_2_arg, clnt2);
				if (result_5 == (bool_t *) NULL) {
					clnt_perror(clnt2, "call failed");
				}
                if (result_8->oferta_actual.objUsuario_comprador_actual.tipo == ADMIN) {
                    printf("La subasta ha sido cerrada sin comprador.\n");
					break;
                }
				if (*result_5==TRUE)
				{
                    printf("La subasta ha sido cerrada. El comprador es: \n");
					// Imprimir los datos del cliente
					printf("Nombres: %s\n", result_8->oferta_actual.objUsuario_comprador_actual.nombres);
					printf("Apellidos: %s\n", result_8->oferta_actual.objUsuario_comprador_actual.apellidos);
					printf("Correo electrónico: %s\n", result_8->oferta_actual.objUsuario_comprador_actual.correo);
					printf("Teléfono: %s\n", result_8->oferta_actual.objUsuario_comprador_actual.telefono);								
					printf("Tipo de usuario: %s\n", result_8->oferta_actual.objUsuario_comprador_actual.tipo == ADMIN ? "ADMIN" : "CLIENTE");
				}else{
					printf("ERROR: La subasta no se pudo cerrar\n");
				}
                break;
            case 2: // Cancelar
                printf("Operacion cancelada.\n");
                break;
            default:
                printf("Opcion invalida.\n");
                break;
        }
    }

}
void ConsultarProductoCodigo(){

}
void consultarProductoActual(){

}
void
gestion_usuarios_1(char *host)
{
	CLIENT *clnt1;
	bool_t  *result_1;
	datos_completos  registrarusuario_1_arg;
	respuesta_login  *result_2;
	datos_login  iniciarsesion_1_arg;
	CLIENT *clnt2;
	bool_t  *result_3;
	nodo_producto  registrar_producto_2_arg;
	vector_productos  *result_4;
	char *listarproductosdisponiblessubastar_2_arg;
	bool_t  *result_5;
	int  abrircerrarsubasta_2_arg;
	vector_productos  *result_6;
	char *listarproductostodos_2_arg;
	nodo_producto  *result_7;
	int  consultarproducto_2_arg;
	nodo_subasta  *result_8;
	char *consultarproductoandvaloractualsubasta_2_arg;
	bool_t  *result_9;
	oferta  ofertarproductosubasta_2_arg;
	int opcion;
	int opcionInicio;


#ifndef	DEBUG
	clnt1 = clnt_create (host, gestion_usuarios, gestion_usuarios_version_1, "udp");
	if (clnt1 == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	clnt2 = clnt_create (host, gestion_subastas, gestion_subastas_version_1, "tcp");
	if (clnt2 == NULL) {
		clnt_pcreateerror(host);
		exit (1);
	}
#endif	/* DEBUG */
	/*result_1 = registrarusuario_1(&registrarusuario_1_arg, clnt1);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror(clnt1, "call failed");
	}
	result_2 = iniciarsesion_1(&iniciarsesion_1_arg, clnt1);
	if (result_2 == (respuesta_login *) NULL) {
		clnt_perror(clnt1, "call failed");
	}*/
	
	//invocacion de los procedimientos remotos
	do
	{
		menuGestionUsuarios();
		printf("\n Digite una opcion: ");
		scanf("%d", &opcion);
		switch (opcion)
		{ 
		case 1:
			registrarusuario_1_arg=registrarAdmin();
			result_1 = registrarusuario_1(&registrarusuario_1_arg, clnt1);
			if (result_1 == (bool_t *) NULL) {
				clnt_perror(clnt1, "call failed");
			} else if (*result_1 == TRUE) {
				printf("\n Usuario registrado exitosamente.");
			}else
			{
				printf("\n Usuario NO fue registrado. capacidad maxima alcanzada");
			}
			

			break;
		case 2:
			do
			{
				printf("\nIngrese el login: ");
				scanf("%s", iniciarsesion_1_arg.login);
				fflush(stdin);
				printf("Ingrese la constrasenia: ");
				scanf("%s", iniciarsesion_1_arg.contrasenia);
				fflush(stdin);
				result_2 = iniciarsesion_1(&iniciarsesion_1_arg, clnt1);
				fflush(stdin);
				printf("\n%s",result_2->mensaje);
				printf("\n%d",result_2->codigo);
				if (result_2 == (respuesta_login *) NULL) {
					clnt_perror(clnt1, "call failed");
				}
				if (result_2->codigo == 0)
				{
					do
					{
						menuSubastaAdmin();
						printf("\n Digite una opcion: ");
						scanf("%d", &opcionInicio);
						switch (opcionInicio)
						{
						case 1:							
							printf("\n====== Registrar Producto ======\n");
							printf("Digite el codigo: "); 
							scanf("%d", &registrar_producto_2_arg.codigoProducto);

							printf("Digite el nombre: "); 
							scanf("%s", registrar_producto_2_arg.nombre);

							printf("Digite el valor: "); 
							scanf("%f",&registrar_producto_2_arg.valor); 
							registrar_producto_2_arg.estadoProd = SI;
							result_3 = registrar_producto_2(&registrar_producto_2_arg, clnt2); 
							if (result_3 == (bool_t *) NULL) { 
								clnt_perror (clnt2, "call failed");
							} 
							else if(*result_3==TRUE)
							{
								printf("\n Producto registrado exitosamente");
							}else{
								printf("\n No se pueden agrgar mas productos o producto repetido");
							}	
							break;
						case 2:
							// Llamar a la función remota para listar los productos disponibles para ofertar
							result_4 = listarproductosdisponiblessubastar_2((void*)&listarproductosdisponiblessubastar_2_arg, clnt2);
							if (result_4 == (vector_productos *) NULL) {
								clnt_perror(clnt2, "call failed");
							}
							// Imprimir la lista de productos
							printf("\n====== Lista de productos a ofertar ======\n");
							int i=0;
							if (result_4->vector_productos != NULL) {
								while (i<MAX_CAN_PROD && result_4->vector_productos[i].codigoProducto != 0)
								{
									printf("Codigo: %d\n", result_4->vector_productos[i].codigoProducto);
									printf("Nombre: %s\n", result_4->vector_productos[i].nombre);
									printf("Actualmente esta disponible para subastar: %s\n", result_4->vector_productos[i].estadoProd == SI ? "SI" : "NO");
									printf("Precio base: %.2f\n", result_4->vector_productos[i].valor);
									printf("====================\n");
									i++;
								}
								
							} 
							if(i==0) 
							{
								printf("No hay productos disponibles para ofertar\n");
							}
							break;
						case 3:
							abrirOCerrarSubasta(result_8,consultarproductoandvaloractualsubasta_2_arg,result_5,abrircerrarsubasta_2_arg,clnt2);
							
							break;
						case 4:
							printf("Digite el codigo: ");
							scanf("%d", &consultarproducto_2_arg);
							
							result_7 = consultarproducto_2(&consultarproducto_2_arg, clnt2);
							if (result_7 == (nodo_producto *) NULL) {
								clnt_perror (clnt2, "call failed");
							}
							else
							{
								if (result_7->codigoProducto==-1)
								{
									printf("No hay un producto registrado con codigo: %d \n",consultarproducto_2_arg);
								}
								else
								{
									printf("\nCodigo: %d", result_7->codigoProducto);
									printf("\nNombre: %s", result_7->nombre);									
									printf("\nActualmente esta disponible para subastar: %s", result_7->estadoProd == SI ? "SI" : "NO");						
									printf("\nPrecio base: %.2f\n", result_7->valor);	
								}								
							}			
							break;
						case 5:
							result_8 = consultarproductoandvaloractualsubasta_2((void*)&consultarproductoandvaloractualsubasta_2_arg, clnt2);
							if (result_8 == (nodo_subasta *) NULL) {
								clnt_perror(clnt2, "call failed");
							}else
							{
								if (result_8->estado == NUEVA || result_8->estado == CERRADA || result_8->prod.codigoProducto==-1) { // Si no hay una subasta actual
        							printf("No hay una subasta abierta actualmente.\n");
								}else
								{
									printf("\nCodigo: %d", result_8->prod.codigoProducto);
									printf("\nNombre: %s", result_8->prod.nombre);						
									printf("\nPrecio actual: %.2f\n", result_8->oferta_actual.valor);
								}
								
							}
									
							break;
						case 6:
							printf("\nSaliendo del programa.\n");				
							break;
						default:
							break;
						}
					} while (opcionInicio != 6);
					
				}
	
			} while (result_2->codigo != 0);
			
			break;
		case 3:
			printf("\nSaliendo del programa.\n");				
			break;

		default:
			printf("\nopcion no valida.");	
			break;
		}
	} while (opcion!=3);
	 
	
	
#ifndef	DEBUG
	clnt_destroy (clnt1);
	clnt_destroy (clnt2);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_usuarios_1 (host);
exit (0);
}
